# Generated by Django 3.0.8 on 2020-09-24 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0052_pagelogentry'),
        ('open_hours', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='branchinfo',
            name='closed_holiday_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page'),
        ),
    ]
